# Generated by Django 5.0.2 on 2024-04-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search_paragraph_logic', '0004_paragraph_token_data_paragraph_word_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordindex',
            name='paragraph',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='WordIndex',
        ),
    ]
